oc label node worker-1.ocp4.cdplab.local cluster.ocs.openshift.io/openshift-storage=''
oc label node worker-2.ocp4.cdplab.local cluster.ocs.openshift.io/openshift-storage=''
oc label node worker-3.ocp4.cdplab.local cluster.ocs.openshift.io/openshift-storage=''
oc label node worker-4.ocp4.cdplab.local cluster.ocs.openshift.io/openshift-storage=''
oc label node worker-5.ocp4.cdplab.local cluster.ocs.openshift.io/openshift-storage=''
